---
# https://github.com/mathiasbynens/dotfiles/blob/master/brew.sh
role:
  # os: darwin
  pkg:
    - name: karabiner-elements
      type: cask
      os: ["darwin16"]
    # Brew unbundle requirement (mas)
    - name: trash
      action: install
  dir:
    - .config/karabiner
  link:
    - ".config/karabiner/karabiner.json:.config/karabiner"
  install:
    # - brew update && brew upgrade
    - brew bundle # --file=Brewfile
  post_install:
    - command: ./.macos
      if: test -z $TRAVIS
    # - brew cleanup
    # - mas uprade
  remove:
    - ./brew-unbundle.sh Brewfile
