---
# https://github.com/mathiasbynens/dotfiles/blob/master/brew.sh
role:
  # os: darwin
  pkg:
    - name: karabiner-elements
      type: cask
      os: ["darwin16"]
    # Brew unbundle requirement (mas)
    - name: trash
      action: install
  dir:
    - .config/karabiner
  link:
    - ".config/karabiner/karabiner.json:.config/karabiner"
  install:
    # - brew update && brew upgrade
    - command: brew bundle # --file=Brewfile
      if: '[ "$DOT_PKG" -eq 1 ]'
  post_install:
    # - brew cleanup
    # - mas uprade
    - command: ./.macos
      if: '[ "$DOT_PKG" -eq 1 ] && [ "$CI" != true ]' # test -z $TRAVIS
  remove:
    - command: ./brew-unbundle.sh Brewfile
      if: '[ "$DOT_PKG" -eq 1 ]'
