---
role:
  # os: ["darwin"]
  # install: brew update && brew upgrade
  pkg: # Formulae
    - cmake
    - coreutils
    - curl --with-openssl
    - diffutils
    - findutils --with-default-names
    - gnu-sed --with-default-names
    - gnutls
    - grep --with-default-names
    - imagemagick --with-webp
    # - lua
    # - luajit
    # - mas # Mac App Store CLI
    - moreutils
    - nmap
    - openssh
    - openssl
    - patchutils
    # - rename
    # - rsync
    - the_silver_searcher
    - trash # rmtrash, debian: trash-cli
    - wget
    - youtube-dl

    # Completions
    - pip-completion
    - vagrant-completion

    # - name: bettertouchtool
    #   type: cask
    - name: bitwarden
      type: cask
    # - name: dropbox
    #   type: cask
    - name: firefox
      type: cask
    - name: caskroom/fonts/font-hack
      type: cask
    # - name: gimp
    #   type: cask
    - name: google-chrome # -canary
      type: cask
    - name: gpg-suite
      type: cask
    - name: karabiner-elements
      type: cask
      os: ["darwin16"]
    # - name: scroll-reverser
    #   type: cask
    - name: little-snitch
      type: cask
    # - name: opera
    #   type: cask
    # - name: robomongo
    #   type: cask
    # - name: sequel-pro
    #   type: cask
    # - name: skype
    #   type: cask
    # - name: slack
    #   type: cask
    # - name: steam
    #   type: cask
    # - name: torbrowser
    #   type: cask
    - name: transmission
      type: cask
    - name: transmit
      type: cask
    # - name: tunnelbear
    #   type: cask
    - name: vagrant
      type: cask
    - name: virtualbox
      type: cask
    - name: vlc
      type: cask
  link:
    - ".config/karabiner/settings.json:.config/karabiner"
